[package]
name = "sidelingo"
version = "0.1.0"
description = "Structures and translates what you copy"
authors = ["mcdp-adk"]
license = "GPL-3.0-only"
edition = "2021"

[features]
desktop-dev = []

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.22"
image = { version = "0.25", default-features = false, features = ["bmp", "png"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-http = "2"
tauri-plugin-single-instance = "2"
windows = { version = "0.62", features = [
    "Win32_Storage_FileSystem",
    "Win32_Globalization",
    "Win32_System_DataExchange",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_UI_WindowsAndMessaging",
    "UI_ViewManagement",
] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
