[package]
name = "sidelingo"
version = "0.1.0"
description = "Structures and translates what you copy"
authors = ["mcdp-adk"]
license = "GPL-3.0-only"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
windows = { version = "0.62", features = [
    "Win32_Globalization",
    "Win32_UI_WindowsAndMessaging",
    "UI_ViewManagement",
] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
